### ISSUE TITLE
Client refusing to connect

### ISSUE THREAD

**Issue by Giftson-S** [vismodo/Remote-Desktop#1]
In the CLIENT the system is refusing to connect.
![Screenshot (1)](https://user-images.githubusercontent.com/72437336/104992823-d48b2a00-5a47-11eb-8ff8-3393e6cb5f60.png)

**Comment by vismodo** [comment]
You need to run the server script on one PC and the client script on another. The socket library is programmed to connect with computers in the LAN. You entered the public IP. On the computer running the server script, type:
```shell
ipconfig
```
Then, you should look for the IP that comes under `IPv4 Address`. Type that as the host on your client.

![image](https://user-images.githubusercontent.com/62926183/104994837-3c8f3f80-5a4b-11eb-8ed8-a3d7a2bc7467.png)

Local IPs always start with `192.168`. What you entered was the Public IP, which socket does not support. In the above image, that IP that I am pointing to is what you should use as the host when prompted on the client.

Also, do note that the server should start running first and should run until all clients are disconnected.

I don't know if you saw my YouTube demo, which shows you how to operate it:

[![img](https://i.ytimg.com/vi/vjxMKJLADIM/hqdefault.jpg?sqp=-oaymwEZCNACELwBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLD7Zt-vm_WYEP1DyuEwR3TdAIpNgw)](https://www.youtube.com/watch?v=vjxMKJLADIM)

**Comment by vismodo** [comment]
The problem was rather easy to solve when I saw that image you put in the issue. You should be using your private IP, not your public one. You tried to use the public IP. I have given the entire solution on GitHub: https://github.com/vismodo/Remote-Desktop/issues/1


Regards,
Vismaya Atreya (vismaya.atreya@outlook.com<mailto:vismaya.atreya@outlook.com>, https://vismaya.us/ )
